// <auto-generated />
using System;
using Blazor.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazor.Server.Migrations
{
    [DbContext(typeof(TerraNovaDbContext))]
    partial class TerraNovaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blazor.Server.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CI");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Comprador");

                    b.HasKey("Id")
                        .HasName("PK__Clientes__3214EC07E317ACD1");

                    b.HasIndex(new[] { "Ci" }, "UQ__Clientes__32149A7A785F14DC")
                        .IsUnique();

                    b.HasIndex(new[] { "Telefono" }, "UQ__Clientes__4EC504804484003C")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Clientes__A9D10534D9AD21D4")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Blazor.Server.Models.Propiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AreaM2")
                        .HasColumnType("float");

                    b.Property<int>("Banios")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Disponible");

                    b.Property<DateTime>("FechaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Garajes")
                        .HasColumnType("int");

                    b.Property<int>("Habitaciones")
                        .HasColumnType("int");

                    b.Property<int>("IdTrabajador")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<double?>("Latitud")
                        .HasColumnType("float");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Venta");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Propieda__3214EC07230E0E80");

                    b.HasIndex("IdTrabajador");

                    b.ToTable("Propiedades");
                });

            modelBuilder.Entity("Blazor.Server.Models.Trabajador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CI");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("FechaContratacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PorcentajeComision")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Trabajad__3214EC0709AD560B");

                    b.HasIndex(new[] { "Ci" }, "UQ__Trabajad__32149A7AD280977B")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Trabajad__A9D10534E566E69C")
                        .IsUnique();

                    b.ToTable("Trabajadores");
                });

            modelBuilder.Entity("Blazor.Server.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ContraseñaHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("IdTrabajador")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Agente");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3214EC0713F400B2");

                    b.HasIndex("IdTrabajador");

                    b.HasIndex(new[] { "NombreUsuario" }, "UQ__Usuarios__6B0F5AE086D65208")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Blazor.Server.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ComisionGenerada")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Completada");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Contado");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdPropiedad")
                        .HasColumnType("int");

                    b.Property<int>("IdTrabajador")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Ventas__3214EC071EE7C768");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdPropiedad");

                    b.HasIndex("IdTrabajador");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Blazor.Server.Models.Visita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Programada");

                    b.Property<DateTime>("FechaVisita")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdPropiedad")
                        .HasColumnType("int");

                    b.Property<int>("IdTrabajador")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Visitas__3214EC0711EE2058");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdPropiedad");

                    b.HasIndex("IdTrabajador");

                    b.ToTable("Visitas");
                });

            modelBuilder.Entity("Blazor.Server.Models.Propiedad", b =>
                {
                    b.HasOne("Blazor.Server.Models.Trabajador", "IdTrabajadorNavigation")
                        .WithMany("Propiedades")
                        .HasForeignKey("IdTrabajador")
                        .IsRequired()
                        .HasConstraintName("FK_Propiedades_Trabajadores");

                    b.Navigation("IdTrabajadorNavigation");
                });

            modelBuilder.Entity("Blazor.Server.Models.Usuario", b =>
                {
                    b.HasOne("Blazor.Server.Models.Trabajador", "IdTrabajadorNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdTrabajador")
                        .HasConstraintName("FK_Usuarios_Trabajadores");

                    b.Navigation("IdTrabajadorNavigation");
                });

            modelBuilder.Entity("Blazor.Server.Models.Venta", b =>
                {
                    b.HasOne("Blazor.Server.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Ventas_Clientes");

                    b.HasOne("Blazor.Server.Models.Propiedad", "IdPropiedadNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdPropiedad")
                        .IsRequired()
                        .HasConstraintName("FK_Ventas_Propiedades");

                    b.HasOne("Blazor.Server.Models.Trabajador", "IdTrabajadorNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdTrabajador")
                        .IsRequired()
                        .HasConstraintName("FK_Ventas_Trabajadores");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdPropiedadNavigation");

                    b.Navigation("IdTrabajadorNavigation");
                });

            modelBuilder.Entity("Blazor.Server.Models.Visita", b =>
                {
                    b.HasOne("Blazor.Server.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Visita")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Visitas_Clientes");

                    b.HasOne("Blazor.Server.Models.Propiedad", "IdPropiedadNavigation")
                        .WithMany("Visita")
                        .HasForeignKey("IdPropiedad")
                        .IsRequired()
                        .HasConstraintName("FK_Visitas_Propiedades");

                    b.HasOne("Blazor.Server.Models.Trabajador", "IdTrabajadorNavigation")
                        .WithMany("Visita")
                        .HasForeignKey("IdTrabajador")
                        .IsRequired()
                        .HasConstraintName("FK_Visitas_Trabajadores");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdPropiedadNavigation");

                    b.Navigation("IdTrabajadorNavigation");
                });

            modelBuilder.Entity("Blazor.Server.Models.Cliente", b =>
                {
                    b.Navigation("Venta");

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("Blazor.Server.Models.Propiedad", b =>
                {
                    b.Navigation("Venta");

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("Blazor.Server.Models.Trabajador", b =>
                {
                    b.Navigation("Propiedades");

                    b.Navigation("Usuarios");

                    b.Navigation("Venta");

                    b.Navigation("Visita");
                });
#pragma warning restore 612, 618
        }
    }
}
